### ISSUE TITLE
Colors of background changes without background color changes sent

### ISSUE THREAD

**Issue by buzztiaan** [folkertvanheusden/termcamng#2]
x

**Comment by folkertvanheusden** [comment]
This had to do with 'bold'. This is now fixed.

**Comment by buzztiaan** [comment]
11:00:14 <@buZz> flok: bijna! :D https://i.imgur.com/XIo8TPA.png
11:00:38 <@buZz> zie de [] en <> op de chatregels en bij /names output

**Comment by buzz** [comment]
Please stop mentioning me in this thread. Thank you!

**Comment by buzztiaan** [comment]
> Please stop mentioning me in this thread. Thank you!

@buzz ok

**Comment by folkertvanheusden** [comment]
Should be fixed in 6402dc05786798c0667285b27c8c58e3121a7acb
